<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.b3dgs</groupId>
        <artifactId>b3dgs-parent</artifactId>
        <version>2.1.0-SNAPSHOT</version>
    </parent>
    <groupId>com.b3dgs.lionengine</groupId>
    <artifactId>lionengine</artifactId>
    <version>11.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>LionEngine</name>
    <description>Java 2D Game Engine</description>
    <url>https://github.com/b3dgs/lionengine</url>
    <scm>
        <url>https://github.com/b3dgs/lionengine</url>
        <connection>scm:git:git@github.com:b3dgs/lionengine.git</connection>
        <developerConnection>scm:git:git@github.com:b3dgs/lionengine.git</developerConnection>
        <tag>HEAD</tag>
    </scm>
    <properties>
        <radial.base-package>com.b3dgs.lionengine</radial.base-package>
    </properties>
    <repositories>
        <repository>
            <id>snapshots</id>
            <url>https://central.sonatype.com/repository/maven-snapshots</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
    <build>
        <plugins>
            <plugin>
                <groupId>com.b3dgs.radialencapsulation</groupId>
                <artifactId>radial-encapsulation-maven-plugin</artifactId>
                <configuration>
                    <maxViolations>0</maxViolations>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
