<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.b3dgs.lionengine</groupId>
        <artifactId>lionengine</artifactId>
        <version>10.0.0</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>
    <groupId>com.b3dgs.lionengine.editor</groupId>
    <artifactId>aggregator</artifactId>
    <packaging>pom</packaging>
    <name>Aggregator</name>
    <modules>
        <module>../../releng/com.b3dgs.lionengine.editor.target</module>

        <module>../../plugins/com.b3dgs.lionengine.core.swt</module>
        <module>../../plugins/com.b3dgs.lionengine.editor</module>
        <module>../../plugins/com.b3dgs.lionengine.editor.object</module>
        <module>../../plugins/com.b3dgs.lionengine.editor.map</module>
        <module>../../plugins/com.b3dgs.lionengine.editor.animation</module>
        <module>../../plugins/com.b3dgs.lionengine.editor.collision</module>
        <module>../../plugins/com.b3dgs.lionengine.editor.pathfinding</module>

        <module>../com.b3dgs.lionengine.editor.repository</module>
        <module>../com.b3dgs.lionengine.editor.product</module>

        <module>../../tests/com.b3dgs.lionengine.core.swt.test</module>
        <module>../../tests/com.b3dgs.lionengine.editor.test</module>
        <module>../../tests/com.b3dgs.lionengine.editor.object.test</module>
        <module>../../tests/com.b3dgs.lionengine.editor.map.test</module>
        <module>../../tests/com.b3dgs.lionengine.editor.animation.test</module>
        <module>../../tests/com.b3dgs.lionengine.editor.collision.test</module>
        <module>../../tests/com.b3dgs.lionengine.editor.pathfinding.test</module>
    </modules>
</project>