import com.vanniktech.maven.publish.AndroidSingleVariantLibrary

plugins {
    id 'com.android.library' version '9.2.1'
    id 'com.vanniktech.maven.publish' version '0.36.0'
    id 'signing'
}

group = 'com.b3dgs.lionengine'
version = '11.0.0-SNAPSHOT'

android {
    namespace 'com.b3dgs.lionengine.android'
    compileSdk 37

    defaultConfig {
        minSdk 21
        targetSdk 37
        multiDexEnabled true
    }

    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

mavenPublishing {
    publishToMavenCentral()
    signAllPublications()

    configure(
        new com.vanniktech.maven.publish.AndroidSingleVariantLibrary()
    )

    coordinates(
        "com.b3dgs.lionengine",
        "lionengine-core-android",
        version.toString()
    )

    pom {
        name.set("LionEngine Core Android")
        description.set("LionEngine Core Android implementation")
        url.set("https://github.com/b3dgs/lionengine")

        licenses {
            license {
                name.set("GNU General Public License (GPL) version 3.0")
                url.set("https://www.gnu.org/licenses/gpl-3.0.txt")
            }
        }

        developers {
            developer {
                id.set("DjThunder")
                name.set("Pierre-Alexandre")
                email.set("contact@b3dgs.com")
            }
        }

        scm {
            url.set("https://github.com/b3dgs/lionengine-core-android")
        }
    }
}

dependencies {
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.5'

    implementation 'com.b3dgs:b3dgs-parent:2.1.0-SNAPSHOT'
    implementation 'com.b3dgs.lionengine:lionengine-core:11.0.0-SNAPSHOT'
}