# This workflow will:
# - compile, sign, sonar project on windows with JDK 17
# - deploy snapshot on maven and upload on FTP

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        jdk: [17]
    runs-on: ${{ matrix.os }}
    env:
      JDK_VERSION: ${{ matrix.jdk }}

    steps:
     - name: Checkout
       uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
       with:
        fetch-depth: 0

     - name: Cache
       uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
       with:
          path: ~/.m2/repository
          key: maven-${{ matrix.os }}-java${{ matrix.jdk }}-${{ hashFiles('**/pom.xml') }}-${{ hashFiles('**/app/build.gradle') }}
          restore-keys: |
            maven-${{ matrix.os }}-java${{ matrix.jdk }}-${{ hashFiles('**/pom.xml') }}-${{ hashFiles('**/app/build.gradle') }}

     - name: Maven
       uses: stCarolas/setup-maven@12eb41b233df95d49b0c11fc1b5bc8312e5d4ce0
       with:
         maven-version: 3.9.14

     - name: JDK
       uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
       with:
         java-version: |
           ${{ matrix.jdk }}
         distribution: 'temurin'
         mvn-toolchain-id: |
           JavaSE-17
         server-id: ossrh
         server-username: MAVEN_USERNAME
         server-password: MAVEN_PASSWORD

     - name: Decode Keystore
       uses: timheuer/base64-to-file@784a1a4a994315802b7d8e2084e116e783d157be
       with:
         fileName: 'android.jks'
         fileDir: 'app/'
         encodedString: ${{ secrets.KEYSTORE_BASE64 }}

     - name: GPG
       uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd
       with:
         gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
         passphrase: ${{ secrets.GPG_PASSPHRASE }}

     - name: Deploy
       uses: coactions/setup-xvfb@b6b4fcfb9f5a895edadc3bc76318fae0ac17c8b3
       with:
         run: mvn clean deploy org.sonarsource.scanner.maven:sonar-maven-plugin:sonar --file lionengine-parent/pom.xml -U -Dgpg.passphrase="$GPG_PASS" -Psign -Dsonar.organization=b3dgs -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=${{ secrets.SONAR_TOKEN }} -Dsonar.projectKey=b3dgs_lionengine
       env:
         MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
         MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
         GPG_PASS: ${{ secrets.GPG_PASSPHRASE }}

     - name: Upload Editor Repository
       uses: SamKirkland/FTP-Deploy-Action@a51268f67f6605236975928ae28b0f7e9971d50a
       with:
         server: ftp.b3dgs.com
         username: ${{ secrets.FTP_USER }}
         password: ${{ secrets.FTP_PASS }}
         local-dir: com.b3dgs.lionengine.editor.repository/target/repository/

     - name: Prepare Editor Product
       run: |
         rmdir /s /q com.b3dgs.lionengine.editor.product\target\products\com.b3dgs.lionengine.editor.product
       shell: cmd

     - name: Upload Editor Product
       uses: dennisameling/ftp-upload-action@f87b6437536013699f24c8674f7246a1e09e8f3d
       with:
         server: ftp.b3dgs.com
         username: ${{ secrets.FTP_USER }}
         password: ${{ secrets.FTP_PASS }}
         local_dir: com.b3dgs.lionengine.editor.product/target/products/
         server_dir: /product/
         secure: false

     - name: Deploy Android
       run: |
         cd lionengine-core-android
         gradlew publishAllPublicationsToMavenRepository -Dgpg.passphrase="$GPG_PASS" -PNEXUS_USERNAME="$NEXUS_USERNAME" -PNEXUS_PASSWORD="$NEXUS_PASSWORD" -PMAVEN_USERNAME="$MAVEN_USERNAME" -PMAVEN_PASSWORD="$MAVEN_PASSWORD" -Pkeystore=android.jks -Pkeystore.alias="$KEYSTORE_ALIAS" -Pkeystore.storepassword="$KEYSTORE_STOREPASS" -Pkeystore.password="$KEYSTORE_PASS"
       shell: cmd
       env:
         MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
         MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
         NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
         NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
         KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
         KEYSTORE_STOREPASS: ${{ secrets.KEYSTORE_STOREPASS }}
         KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
         GPG_PASS: ${{ secrets.GPG_PASSPHRASE }}
